"""initial schema

Revision ID: 4b07fddd60af
Revises: 
Create Date: 2026-02-07 01:43:11.441789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b07fddd60af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value_json', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_app_settings_key', 'app_settings', ['key'], unique=True)
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=False)
    op.create_index(op.f('ix_app_settings_updated_at'), 'app_settings', ['updated_at'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload_json', sa.String(), nullable=True),
    sa.Column('result_json', sa.String(), nullable=True),
    sa.Column('log_path', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_type_status_created', 'jobs', ['job_type', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_finished_at'), 'jobs', ['finished_at'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_started_at'), 'jobs', ['started_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_updated_at'), 'jobs', ['updated_at'], unique=False)
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('display_title', sa.String(), nullable=True),
    sa.Column('one_liner', sa.String(), nullable=True),
    sa.Column('golden_line', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('pdf_sha256', sa.String(), nullable=True),
    sa.Column('raw_text_path', sa.String(), nullable=True),
    sa.Column('content_explain_cn', sa.String(), nullable=True),
    sa.Column('image_captions_json', sa.String(), nullable=True),
    sa.Column('meta_json', sa.String(), nullable=True),
    sa.Column('content_sha256', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_papers_source_external', 'papers', ['source', 'external_id'], unique=True)
    op.create_index(op.f('ix_papers_content_sha256'), 'papers', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_papers_created_at'), 'papers', ['created_at'], unique=False)
    op.create_index(op.f('ix_papers_day'), 'papers', ['day'], unique=False)
    op.create_index(op.f('ix_papers_external_id'), 'papers', ['external_id'], unique=False)
    op.create_index(op.f('ix_papers_source'), 'papers', ['source'], unique=False)
    op.create_table('paper_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('negative_prompt', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('url_path', sa.String(), nullable=True),
    sa.Column('local_path', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('meta_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_paper_images_paper_kind_provider_order', 'paper_images', ['paper_id', 'kind', 'provider', 'order_idx'], unique=True)
    op.create_index(op.f('ix_paper_images_created_at'), 'paper_images', ['created_at'], unique=False)
    op.create_index(op.f('ix_paper_images_enabled'), 'paper_images', ['enabled'], unique=False)
    op.create_index(op.f('ix_paper_images_kind'), 'paper_images', ['kind'], unique=False)
    op.create_index(op.f('ix_paper_images_order_idx'), 'paper_images', ['order_idx'], unique=False)
    op.create_index(op.f('ix_paper_images_paper_id'), 'paper_images', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_images_provider'), 'paper_images', ['provider'], unique=False)
    op.create_index(op.f('ix_paper_images_sha256'), 'paper_images', ['sha256'], unique=False)
    op.create_index(op.f('ix_paper_images_status'), 'paper_images', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_images_status'), table_name='paper_images')
    op.drop_index(op.f('ix_paper_images_sha256'), table_name='paper_images')
    op.drop_index(op.f('ix_paper_images_provider'), table_name='paper_images')
    op.drop_index(op.f('ix_paper_images_paper_id'), table_name='paper_images')
    op.drop_index(op.f('ix_paper_images_order_idx'), table_name='paper_images')
    op.drop_index(op.f('ix_paper_images_kind'), table_name='paper_images')
    op.drop_index(op.f('ix_paper_images_enabled'), table_name='paper_images')
    op.drop_index(op.f('ix_paper_images_created_at'), table_name='paper_images')
    op.drop_index('idx_paper_images_paper_kind_provider_order', table_name='paper_images')
    op.drop_table('paper_images')
    op.drop_index(op.f('ix_papers_source'), table_name='papers')
    op.drop_index(op.f('ix_papers_external_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_day'), table_name='papers')
    op.drop_index(op.f('ix_papers_created_at'), table_name='papers')
    op.drop_index(op.f('ix_papers_content_sha256'), table_name='papers')
    op.drop_index('idx_papers_source_external', table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_jobs_updated_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_started_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_finished_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index('idx_jobs_type_status_created', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_app_settings_updated_at'), table_name='app_settings')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_index('idx_app_settings_key', table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
