"""bilingual en fields

Revision ID: d27df05f0470
Revises: fd84f4a0755a
Create Date: 2026-02-11 15:26:10.535049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd27df05f0470'
down_revision: Union[str, None] = 'fd84f4a0755a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper_images', schema=None) as batch_op:
        # Non-null column on an existing SQLite table needs a default.
        batch_op.add_column(sa.Column('lang', sa.String(), nullable=False, server_default='zh'))
        batch_op.drop_index('idx_paper_images_paper_kind_provider_order')
        batch_op.create_index(
            'idx_paper_images_paper_kind_provider_lang_order',
            ['paper_id', 'kind', 'provider', 'lang', 'order_idx'],
            unique=True,
        )
        batch_op.create_index(batch_op.f('ix_paper_images_lang'), ['lang'], unique=False)

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('one_liner_en', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('content_explain_en', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_captions_en_json', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('image_captions_en_json')
        batch_op.drop_column('content_explain_en')
        batch_op.drop_column('one_liner_en')

    with op.batch_alter_table('paper_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_images_lang'))
        batch_op.drop_index('idx_paper_images_paper_kind_provider_lang_order')
        batch_op.create_index('idx_paper_images_paper_kind_provider_order', ['paper_id', 'kind', 'provider', 'order_idx'], unique=1)
        batch_op.drop_column('lang')

    # ### end Alembic commands ###
